version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pg-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_course
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: online_course
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
